name: Deploy Hugo Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Building Hugo Pages
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo
        working-directory: ./cp-hugo-pages
        run: |
          hugo --minify --baseURL="https://${{ github.repository_owner }}.github.io/coding-pirates-hugo-templates"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cp-hugo-pages/public
